export {
  CATEGORY_NAMES,
  GLOBAL_CHANNELS,
  LOG_CHANNELS,
  START_CHANNELS,
  UNIVERSITY_CHANNELS,
  normalizePlan,
  mergePersistedDivisionsIntoPlan,
  roleSpecs,
  globalForumTags,
  peopleDirectoryForumTags,
  universityForumTags,
  legacyChannelAliasesForUniversity,
  legacyDivisionTextAliases,
  legacyDivisionVoiceAliases,
} from './plan.js';
export {
  stripDangerousHumanPermissions,
  startHereOverwrites,
  privateBaseOverwrites,
  globalGeneralOverwrites,
  globalVoiceOverwrites,
  globalAnnouncementOverwrites,
  globalBotLogOverwrites,
  globalBoardOverwrites,
  memberForumOverwrites,
  showcaseForumOverwrites,
  peopleDirectoryForumOverwrites,
  universityGeneralOverwrites,
  universityVoiceOverwrites,
  universityAnnouncementOverwrites,
  universityBoardOverwrites,
  universityBotLogOverwrites,
  universityExecutiveOverwrites,
  universityShowcaseOverwrites,
  divisionTextOverwrites,
  divisionVoiceOverwrites,
  logsOverwrites,
} from './permissions.js';
export { normalizeComparableName, ignoredLegacyWarnings } from './legacy.js';
export { reconcileExistingMembers, recognizeMemberFromRoles } from './members.js';
export {
  provisionDiscord,
  createProvisionClient,
  DiscordProvisioner,
  universityChannelPositions,
} from './discord.js';
