-- Upgrade the legacy BAINSA Discord schema to the V1 university-scoped contract.
-- This migration is intentionally additive/idempotent: legacy rows and applied
-- migration records are preserved, while old Discord resource columns are
-- renamed or backfilled into the new names.

CREATE TABLE IF NOT EXISTS schema_migrations (
  filename text PRIMARY KEY,
  checksum char(64) NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT now(),
  execution_ms integer NOT NULL
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS universities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  discord_role_id text,
  category_id text,
  announcements_channel_id text,
  board_channel_id text,
  showcase_channel_id text,
  onboarding_review_channel_id text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS divisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university_id bigint NOT NULL REFERENCES universities(id),
  name text NOT NULL,
  member_role_id text,
  head_role_id text,
  text_channel_id text,
  voice_channel_id text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'universities'
      AND column_name = 'discord_category_id'
  ) AND NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'universities'
      AND column_name = 'category_id'
  ) THEN
    ALTER TABLE universities RENAME COLUMN discord_category_id TO category_id;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'universities'
      AND column_name = 'discord_board_channel_id'
  ) AND NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'universities'
      AND column_name = 'board_channel_id'
  ) THEN
    ALTER TABLE universities RENAME COLUMN discord_board_channel_id TO board_channel_id;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'divisions'
      AND column_name = 'discord_general_channel_id'
  ) AND NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'divisions'
      AND column_name = 'text_channel_id'
  ) THEN
    ALTER TABLE divisions RENAME COLUMN discord_general_channel_id TO text_channel_id;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'divisions'
      AND column_name = 'discord_voice_channel_id'
  ) AND NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'divisions'
      AND column_name = 'voice_channel_id'
  ) THEN
    ALTER TABLE divisions RENAME COLUMN discord_voice_channel_id TO voice_channel_id;
  END IF;
END;
$$;

ALTER TABLE universities ADD COLUMN IF NOT EXISTS slug text;
ALTER TABLE universities ADD COLUMN IF NOT EXISTS discord_role_id text;
ALTER TABLE universities ADD COLUMN IF NOT EXISTS category_id text;
ALTER TABLE universities ADD COLUMN IF NOT EXISTS announcements_channel_id text;
ALTER TABLE universities ADD COLUMN IF NOT EXISTS board_channel_id text;
ALTER TABLE universities ADD COLUMN IF NOT EXISTS showcase_channel_id text;
ALTER TABLE universities ADD COLUMN IF NOT EXISTS onboarding_review_channel_id text;
ALTER TABLE universities ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true;
ALTER TABLE universities ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE universities ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE divisions ADD COLUMN IF NOT EXISTS slug text;
ALTER TABLE divisions ADD COLUMN IF NOT EXISTS member_role_id text;
ALTER TABLE divisions ADD COLUMN IF NOT EXISTS head_role_id text;
ALTER TABLE divisions ADD COLUMN IF NOT EXISTS text_channel_id text;
ALTER TABLE divisions ADD COLUMN IF NOT EXISTS voice_channel_id text;
ALTER TABLE divisions ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true;
ALTER TABLE divisions ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE divisions ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'universities'
      AND column_name = 'discord_category_id'
  ) THEN
    UPDATE universities
    SET category_id = COALESCE(category_id, discord_category_id)
    WHERE category_id IS NULL;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'universities'
      AND column_name = 'discord_board_channel_id'
  ) THEN
    UPDATE universities
    SET board_channel_id = COALESCE(board_channel_id, discord_board_channel_id)
    WHERE board_channel_id IS NULL;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'divisions'
      AND column_name = 'discord_general_channel_id'
  ) THEN
    UPDATE divisions
    SET text_channel_id = COALESCE(text_channel_id, discord_general_channel_id)
    WHERE text_channel_id IS NULL;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'divisions'
      AND column_name = 'discord_voice_channel_id'
  ) THEN
    UPDATE divisions
    SET voice_channel_id = COALESCE(voice_channel_id, discord_voice_channel_id)
    WHERE voice_channel_id IS NULL;
  END IF;
END;
$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'universities'
      AND column_name = 'is_cross_university'
  ) THEN
    UPDATE universities
    SET active = false,
        updated_at = now()
    WHERE COALESCE(is_cross_university, false) = true
      AND active = true;
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.universities'::regclass
      AND contype = 'p'
  ) THEN
    ALTER TABLE universities ADD CONSTRAINT universities_pkey PRIMARY KEY (id);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'universities'
      AND column_name = 'id'
      AND identity_generation IS NOT NULL
  ) THEN
    BEGIN
      ALTER TABLE universities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    EXCEPTION
      WHEN duplicate_object OR object_not_in_prerequisite_state THEN
        NULL;
    END;
  END IF;

  IF pg_get_serial_sequence('universities', 'id') IS NOT NULL
     AND (SELECT MAX(id) FROM universities) IS NOT NULL THEN
    PERFORM setval(
      pg_get_serial_sequence('universities', 'id'),
      (SELECT MAX(id) FROM universities),
      true
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.divisions'::regclass
      AND contype = 'p'
  ) THEN
    ALTER TABLE divisions ADD CONSTRAINT divisions_pkey PRIMARY KEY (id);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'divisions'
      AND column_name = 'id'
      AND identity_generation IS NOT NULL
  ) THEN
    BEGIN
      ALTER TABLE divisions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    EXCEPTION
      WHEN duplicate_object OR object_not_in_prerequisite_state THEN
        NULL;
    END;
  END IF;

  IF pg_get_serial_sequence('divisions', 'id') IS NOT NULL
     AND (SELECT MAX(id) FROM divisions) IS NOT NULL THEN
    PERFORM setval(
      pg_get_serial_sequence('divisions', 'id'),
      (SELECT MAX(id) FROM divisions),
      true
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.divisions'::regclass
      AND conname = 'divisions_university_id_fkey'
  ) THEN
    ALTER TABLE divisions
      ADD CONSTRAINT divisions_university_id_fkey
      FOREIGN KEY (university_id) REFERENCES universities(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.divisions'::regclass
      AND conname = 'divisions_id_university_id_unique'
  ) THEN
    ALTER TABLE divisions
      ADD CONSTRAINT divisions_id_university_id_unique UNIQUE (id, university_id);
  END IF;
END;
$$;

ALTER TABLE universities ALTER COLUMN name SET NOT NULL;
ALTER TABLE universities ALTER COLUMN active SET NOT NULL;
ALTER TABLE universities ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE universities ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE divisions ALTER COLUMN university_id SET NOT NULL;
ALTER TABLE divisions ALTER COLUMN name SET NOT NULL;
ALTER TABLE divisions ALTER COLUMN active SET NOT NULL;
ALTER TABLE divisions ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE divisions ALTER COLUMN updated_at SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS universities_name_ci_unique
  ON universities (lower(name));

CREATE UNIQUE INDEX IF NOT EXISTS divisions_university_name_ci_unique
  ON divisions (university_id, lower(name));

CREATE INDEX IF NOT EXISTS universities_active_idx
  ON universities (active, name);

CREATE INDEX IF NOT EXISTS divisions_university_active_idx
  ON divisions (university_id, active, name);

DROP TRIGGER IF EXISTS universities_set_updated_at ON universities;
CREATE TRIGGER universities_set_updated_at
BEFORE UPDATE ON universities
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS divisions_set_updated_at ON divisions;
CREATE TRIGGER divisions_set_updated_at
BEFORE UPDATE ON divisions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS members (
  discord_user_id text PRIMARY KEY,
  member_type text NOT NULL DEFAULT 'researcher',
  university_id bigint NOT NULL REFERENCES universities(id),
  status text NOT NULL DEFAULT 'active',
  notes text,
  joined_at timestamptz NOT NULL DEFAULT now(),
  removed_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE members ADD COLUMN IF NOT EXISTS member_type text NOT NULL DEFAULT 'researcher';
ALTER TABLE members ADD COLUMN IF NOT EXISTS university_id bigint;
ALTER TABLE members ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active';
ALTER TABLE members ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE members ADD COLUMN IF NOT EXISTS joined_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE members ADD COLUMN IF NOT EXISTS removed_at timestamptz;
ALTER TABLE members ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.members'::regclass
      AND conname = 'members_member_type_check'
  ) THEN
    ALTER TABLE members
      ADD CONSTRAINT members_member_type_check
      CHECK (member_type IN ('researcher', 'alumni'));
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.members'::regclass
      AND conname = 'members_status_check'
  ) THEN
    ALTER TABLE members
      ADD CONSTRAINT members_status_check
      CHECK (status IN ('active', 'removed'));
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.members'::regclass
      AND conname = 'members_university_id_fkey'
  ) THEN
    ALTER TABLE members
      ADD CONSTRAINT members_university_id_fkey
      FOREIGN KEY (university_id) REFERENCES universities(id);
  END IF;
END;
$$;

ALTER TABLE members ALTER COLUMN member_type SET NOT NULL;
ALTER TABLE members ALTER COLUMN university_id SET NOT NULL;
ALTER TABLE members ALTER COLUMN status SET NOT NULL;
ALTER TABLE members ALTER COLUMN joined_at SET NOT NULL;
ALTER TABLE members ALTER COLUMN updated_at SET NOT NULL;

CREATE INDEX IF NOT EXISTS members_university_status_idx
  ON members (university_id, status, member_type);

DROP TRIGGER IF EXISTS members_set_updated_at ON members;
CREATE TRIGGER members_set_updated_at
BEFORE UPDATE ON members
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS member_divisions (
  discord_user_id text NOT NULL REFERENCES members(discord_user_id) ON DELETE CASCADE,
  division_id bigint NOT NULL REFERENCES divisions(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (discord_user_id, division_id)
);

CREATE INDEX IF NOT EXISTS member_divisions_division_id_idx
  ON member_divisions (division_id);

CREATE OR REPLACE FUNCTION validate_member_division_university()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM members
    JOIN divisions
      ON divisions.id = NEW.division_id
     AND divisions.university_id = members.university_id
    WHERE members.discord_user_id = NEW.discord_user_id
  ) THEN
    RAISE EXCEPTION 'member division must belong to the member university';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS member_divisions_validate_university ON member_divisions;
CREATE TRIGGER member_divisions_validate_university
BEFORE INSERT OR UPDATE ON member_divisions
FOR EACH ROW
EXECUTE FUNCTION validate_member_division_university();

CREATE TABLE IF NOT EXISTS board_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discord_user_id text NOT NULL REFERENCES members(discord_user_id),
  university_id bigint REFERENCES universities(id),
  division_id bigint REFERENCES divisions(id),
  role text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.board_assignments'::regclass
      AND conname = 'board_assignments_role_check'
  ) THEN
    ALTER TABLE board_assignments
      ADD CONSTRAINT board_assignments_role_check
      CHECK (role IN ('head', 'vice_president', 'president', 'global_president'));
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.board_assignments'::regclass
      AND conname = 'board_assignments_shape_check'
  ) THEN
    ALTER TABLE board_assignments
      ADD CONSTRAINT board_assignments_shape_check
      CHECK (
        (
          role = 'global_president'
          AND university_id IS NULL
          AND division_id IS NULL
        )
        OR (
          role = 'head'
          AND university_id IS NOT NULL
          AND division_id IS NOT NULL
        )
        OR (
          role IN ('vice_president', 'president')
          AND university_id IS NOT NULL
          AND division_id IS NULL
        )
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.board_assignments'::regclass
      AND conname = 'board_assignments_division_university_fkey'
  ) THEN
    ALTER TABLE board_assignments
      ADD CONSTRAINT board_assignments_division_university_fkey
      FOREIGN KEY (division_id, university_id) REFERENCES divisions(id, university_id);
  END IF;
END;
$$;

CREATE UNIQUE INDEX IF NOT EXISTS board_assignments_active_member_role_unique
  ON board_assignments (
    discord_user_id,
    role,
    COALESCE(university_id, 0),
    COALESCE(division_id, 0)
  )
  WHERE active = true;

CREATE UNIQUE INDEX IF NOT EXISTS board_assignments_active_head_per_division_unique
  ON board_assignments (division_id)
  WHERE active = true AND role = 'head';

CREATE UNIQUE INDEX IF NOT EXISTS board_assignments_active_president_per_university_unique
  ON board_assignments (university_id)
  WHERE active = true AND role = 'president';

CREATE UNIQUE INDEX IF NOT EXISTS board_assignments_active_vp_per_university_unique
  ON board_assignments (university_id)
  WHERE active = true AND role = 'vice_president';

CREATE INDEX IF NOT EXISTS board_assignments_member_active_idx
  ON board_assignments (discord_user_id, active);

CREATE INDEX IF NOT EXISTS board_assignments_university_active_idx
  ON board_assignments (university_id, active, role);

DROP TRIGGER IF EXISTS board_assignments_set_updated_at ON board_assignments;
CREATE TRIGGER board_assignments_set_updated_at
BEFORE UPDATE ON board_assignments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  university_id bigint NOT NULL REFERENCES universities(id),
  division_id bigint NOT NULL,
  channel_id text,
  showcase_thread_id text,
  status text NOT NULL DEFAULT 'active',
  start_date date NOT NULL,
  expected_end date NOT NULL,
  notes text,
  outcome text,
  final_notes text,
  closed_at timestamptz,
  archived_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT projects_division_university_fkey
    FOREIGN KEY (division_id, university_id) REFERENCES divisions(id, university_id)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.projects'::regclass
      AND conname = 'projects_status_check'
  ) THEN
    ALTER TABLE projects
      ADD CONSTRAINT projects_status_check
      CHECK (status IN ('active', 'paused', 'completed', 'archived'));
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.projects'::regclass
      AND conname = 'projects_expected_end_check'
  ) THEN
    ALTER TABLE projects
      ADD CONSTRAINT projects_expected_end_check
      CHECK (expected_end >= start_date);
  END IF;
END;
$$;

ALTER TABLE projects ALTER COLUMN start_date SET NOT NULL;
ALTER TABLE projects ALTER COLUMN expected_end SET NOT NULL;

CREATE INDEX IF NOT EXISTS projects_university_division_status_idx
  ON projects (university_id, division_id, status);

CREATE INDEX IF NOT EXISTS projects_status_created_idx
  ON projects (status, created_at);

DROP TRIGGER IF EXISTS projects_set_updated_at ON projects;
CREATE TRIGGER projects_set_updated_at
BEFORE UPDATE ON projects
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS project_people (
  project_id bigint NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  discord_user_id text NOT NULL REFERENCES members(discord_user_id),
  role text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (project_id, discord_user_id)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.project_people'::regclass
      AND conname = 'project_people_role_check'
  ) THEN
    ALTER TABLE project_people
      ADD CONSTRAINT project_people_role_check
      CHECK (role IN ('member', 'supervisor', 'board_liaison'));
  END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS project_people_user_role_idx
  ON project_people (discord_user_id, role);

DROP TRIGGER IF EXISTS project_people_set_updated_at ON project_people;
CREATE TRIGGER project_people_set_updated_at
BEFORE UPDATE ON project_people
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS onboarding_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discord_user_id text NOT NULL,
  member_type text,
  university_id bigint REFERENCES universities(id),
  division_ids bigint[] NOT NULL DEFAULT ARRAY[]::bigint[],
  status text NOT NULL DEFAULT 'draft',
  review_message_id text,
  reviewed_by text,
  review_reason text,
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE onboarding_requests ADD COLUMN IF NOT EXISTS reviewed_at timestamptz;
ALTER TABLE onboarding_requests ALTER COLUMN member_type DROP NOT NULL;
ALTER TABLE onboarding_requests ALTER COLUMN university_id DROP NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.onboarding_requests'::regclass
      AND conname = 'onboarding_requests_member_type_check'
  ) THEN
    ALTER TABLE onboarding_requests
      ADD CONSTRAINT onboarding_requests_member_type_check
      CHECK (member_type IN ('researcher', 'alumni'));
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.onboarding_requests'::regclass
      AND conname = 'onboarding_requests_status_check'
  ) THEN
    ALTER TABLE onboarding_requests
      ADD CONSTRAINT onboarding_requests_status_check
      CHECK (status IN ('draft', 'pending', 'approved', 'rejected', 'cancelled'));
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.onboarding_requests'::regclass
      AND conname = 'onboarding_requests_shape_check'
  ) THEN
    ALTER TABLE onboarding_requests
      ADD CONSTRAINT onboarding_requests_shape_check
      CHECK (
        status IN ('draft', 'cancelled')
        OR (member_type IS NOT NULL AND university_id IS NOT NULL)
      );
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION validate_onboarding_divisions()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  normalized_ids bigint[];
  input_count integer;
  distinct_count integer;
BEGIN
  normalized_ids := COALESCE(NEW.division_ids, ARRAY[]::bigint[]);
  NEW.division_ids := normalized_ids;

  SELECT COUNT(*), COUNT(DISTINCT division_id)
  INTO input_count, distinct_count
  FROM unnest(normalized_ids) AS division_id;

  IF input_count <> distinct_count THEN
    RAISE EXCEPTION 'onboarding division_ids cannot contain duplicates';
  END IF;

  IF NEW.member_type = 'alumni' AND cardinality(normalized_ids) <> 0 THEN
    RAISE EXCEPTION 'alumni onboarding requests must not include divisions';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM unnest(normalized_ids) AS requested_division_id
    LEFT JOIN divisions
      ON divisions.id = requested_division_id
     AND divisions.university_id = NEW.university_id
    WHERE divisions.id IS NULL
  ) THEN
    RAISE EXCEPTION 'onboarding division_ids must belong to the selected university';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS onboarding_requests_validate_divisions ON onboarding_requests;
CREATE TRIGGER onboarding_requests_validate_divisions
BEFORE INSERT OR UPDATE ON onboarding_requests
FOR EACH ROW
EXECUTE FUNCTION validate_onboarding_divisions();

CREATE UNIQUE INDEX IF NOT EXISTS onboarding_requests_one_open_per_user_unique
  ON onboarding_requests (discord_user_id)
  WHERE status IN ('draft', 'pending');

CREATE INDEX IF NOT EXISTS onboarding_requests_university_status_idx
  ON onboarding_requests (university_id, status, created_at);

DROP TRIGGER IF EXISTS onboarding_requests_set_updated_at ON onboarding_requests;
CREATE TRIGGER onboarding_requests_set_updated_at
BEFORE UPDATE ON onboarding_requests
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS audit_log (
  actor_discord_user_id text NOT NULL,
  action text NOT NULL,
  target_type text NOT NULL,
  target_id text,
  university_id bigint REFERENCES universities(id),
  before_state jsonb,
  after_state jsonb,
  reason text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audit_log_actor_created_idx
  ON audit_log (actor_discord_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS audit_log_target_idx
  ON audit_log (target_type, target_id, created_at DESC);

CREATE INDEX IF NOT EXISTS audit_log_university_created_idx
  ON audit_log (university_id, created_at DESC);

CREATE TABLE IF NOT EXISTS provisioned_messages (
  guild_id text NOT NULL,
  channel_id text NOT NULL,
  content_key text NOT NULL,
  message_id text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (guild_id, channel_id, content_key)
);

DROP TRIGGER IF EXISTS provisioned_messages_set_updated_at ON provisioned_messages;
CREATE TRIGGER provisioned_messages_set_updated_at
BEFORE UPDATE ON provisioned_messages
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
