-- Notifications are tied to the audit event that authorized them.  The
-- original audit table predates generated identifiers, so establish one here
-- before using it as a foreign-key target.  `SET id = DEFAULT` also assigns
-- identifiers to any historical audit rows when this migration is introduced
-- to an existing installation.
ALTER TABLE audit_log
  ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;

UPDATE audit_log
SET id = DEFAULT
WHERE id IS NULL;

ALTER TABLE audit_log
  ALTER COLUMN id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.audit_log'::regclass
      AND contype = 'p'
  ) THEN
    ALTER TABLE audit_log
      ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS transition_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  audit_id bigint NOT NULL REFERENCES audit_log(id) ON DELETE CASCADE,
  recipient_discord_user_id text NOT NULL,
  kind text NOT NULL,
  university_id bigint REFERENCES universities(id),
  related_entity_type text NOT NULL,
  related_entity_id text,
  payload jsonb NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  ready boolean NOT NULL DEFAULT true,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'sending', 'delivered', 'failed', 'uncertain')),
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  retryable boolean NOT NULL DEFAULT true,
  next_attempt_at timestamptz NOT NULL DEFAULT now(),
  claimed_at timestamptz,
  delivered_at timestamptz,
  last_error_code text,
  last_error_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (audit_id, recipient_discord_user_id, kind)
);

CREATE INDEX IF NOT EXISTS transition_notifications_delivery_idx
  ON transition_notifications (next_attempt_at, id)
  WHERE ready = true AND status IN ('pending', 'failed') AND retryable = true;

CREATE INDEX IF NOT EXISTS transition_notifications_university_health_idx
  ON transition_notifications (university_id, status, updated_at DESC)
  WHERE status IN ('pending', 'failed', 'uncertain');

CREATE INDEX IF NOT EXISTS transition_notifications_target_idx
  ON transition_notifications (related_entity_type, related_entity_id, id);
