export const GUIDE_TOPICS = Object.freeze({
  MEMBERS: 'members',
  PROJECTS: 'projects',
  LOOKUPS: 'lookups',
  RULES: 'rules',
});

function entry({
  command,
  title,
  topic,
  summary,
  scopeKind,
  before,
  inputs,
  success,
  activity,
}) {
  return Object.freeze({
    command,
    title,
    topic,
    summary,
    scopeKind,
    before: Object.freeze(before),
    inputs: Object.freeze(inputs),
    success,
    activity,
  });
}

export const GUIDE_CATALOG = Object.freeze([
  entry({
    command: 'member-add',
    title: 'Add a university member',
    topic: GUIDE_TOPICS.MEMBERS,
    summary: 'Add or initialise a Researcher or Alumni member.',
    scopeKind: 'university',
    before: ['Confirm the member type and university.', 'For Researchers, know the divisions they should join.'],
    inputs: ['Member', 'Member type', 'University', 'Optional divisions and internal notes'],
    success: 'The member record and managed Discord roles are updated.',
    activity: 'A concise member-added entry is posted in #bot-log; internal notes are never shown.',
  }),
  entry({
    command: 'member-update',
    title: 'Update a university member',
    topic: GUIDE_TOPICS.MEMBERS,
    summary: 'Change a member type, university, divisions, or internal notes.',
    scopeKind: 'university',
    before: ['Check that the change will not make the member ineligible for an active project.'],
    inputs: ['Member', 'Only the fields that should change'],
    success: 'The member record and managed Discord roles are reconciled.',
    activity: 'Visible membership changes are posted in #bot-log. A notes-only update stays private.',
  }),
  entry({
    command: 'member-remove',
    title: 'Remove a member',
    topic: GUIDE_TOPICS.MEMBERS,
    summary: 'Remove a member from the Discord server and deactivate their access.',
    scopeKind: 'university',
    before: ['Confirm the target carefully; this immediately removes them from the server.'],
    inputs: ['Member', 'Optional private reason'],
    success: 'Membership, board assignments, divisions, and project access are cleaned up.',
    activity: 'The removal is posted in #bot-log without the private reason.',
  }),
  entry({
    command: 'member-info',
    title: 'View member information',
    topic: GUIDE_TOPICS.LOOKUPS,
    summary: 'View a member profile, divisions, board roles, and active projects.',
    scopeKind: 'university',
    before: ['The target must be inside your permitted university scope.'],
    inputs: ['Optional member; when omitted, the bot uses you where supported'],
    success: 'The member information is shown only to you.',
    activity: 'Nothing is posted in #bot-log.',
  }),
  entry({
    command: 'division-create',
    title: 'Create a division',
    topic: GUIDE_TOPICS.MEMBERS,
    summary: 'Create a division, its roles, its first Head, and optional channels.',
    scopeKind: 'university',
    before: ['Choose a unique division name, colour, initial Head, and required channels.'],
    inputs: ['University', 'Division name and colour', 'Initial Head', 'Text/voice channel choices'],
    success: 'The division, roles, Head assignment, and selected channels are created.',
    activity: 'The new division, Head, and created channels are posted in #bot-log.',
  }),
  entry({
    command: 'division-update',
    title: 'Update a division',
    topic: GUIDE_TOPICS.MEMBERS,
    summary: 'Update a division name or color and reconcile managed Discord roles and channels.',
    scopeKind: 'university',
    before: ['Choose an unused division name when renaming, and at least one changed value.'],
    inputs: ['University', 'Current division', 'Optional new name', 'Optional new color'],
    success: 'The database and managed Discord resources use the updated name and color.',
    activity: 'The changed name and color are posted in #bot-log.',
  }),
  entry({
    command: 'division-add-member',
    title: 'Add a division member',
    topic: GUIDE_TOPICS.MEMBERS,
    summary: 'Add an active Researcher to a division.',
    scopeKind: 'division',
    before: ['The member must be eligible as a Researcher in the selected university.'],
    inputs: ['Member', 'University', 'Division'],
    success: 'The division membership and Discord access role are added.',
    activity: 'The member and division are posted in #bot-log.',
  }),
  entry({
    command: 'division-remove-member',
    title: 'Remove a division member',
    topic: GUIDE_TOPICS.MEMBERS,
    summary: 'Remove a member from a division while retaining university membership.',
    scopeKind: 'division',
    before: ['The member cannot still require that division through an active project.'],
    inputs: ['Member', 'University', 'Division', 'Optional private reason'],
    success: 'The division relationship and Discord access role are removed.',
    activity: 'The member and division are posted in #bot-log without the private reason.',
  }),
  entry({
    command: 'board-assign',
    title: 'Assign a board role',
    topic: GUIDE_TOPICS.MEMBERS,
    summary: 'Appoint a Head or university executive.',
    scopeKind: 'university',
    before: ['A division is required for a Head appointment.', 'A President or Global President can appoint a President.'],
    inputs: ['Member', 'University', 'Board role', 'Division for a Head'],
    success: 'The board assignment and managed Discord roles are reconciled.',
    activity: 'The member, role, and scope are posted in #bot-log.',
  }),
  entry({
    command: 'board-remove',
    title: 'Remove a board role',
    topic: GUIDE_TOPICS.MEMBERS,
    summary: 'Remove a board appointment while retaining base membership.',
    scopeKind: 'university',
    before: ['A President or Global President can remove a President.'],
    inputs: ['Member', 'University', 'Board role', 'Optional division and private reason'],
    success: 'The board assignment and managed Discord role are removed.',
    activity: 'The member, role, and scope are posted in #bot-log without the private reason.',
  }),
  entry({
    command: 'board-info',
    title: 'View a university board',
    topic: GUIDE_TOPICS.LOOKUPS,
    summary: 'View active board roles and Discord-role consistency.',
    scopeKind: 'university',
    before: ['Choose a university within your board scope.'],
    inputs: ['University'],
    success: 'The board roster is shown only to you.',
    activity: 'Nothing is posted in #bot-log.',
  }),
  entry({
    command: 'project-create',
    title: 'Create a project',
    topic: GUIDE_TOPICS.PROJECTS,
    summary: 'Create a private, division-scoped project and Discord channel.',
    scopeKind: 'division',
    before: [
      'Members must be active Researchers in the selected division.',
      'Supervisors must be active members of the selected university.',
      'Prepare start and expected-end dates in YYYY-MM-DD format.',
    ],
    inputs: ['Name', 'University and division', 'Dates', 'Optional private notes', 'Native member and supervisor selectors'],
    success: 'The project is committed and its private Discord channel is created or queued for reconciliation.',
    activity: 'The project, team, timeline, and Discord state are posted in #bot-log; notes are omitted.',
  }),
  entry({
    command: 'project-add-member',
    title: 'Add or change a project participant',
    topic: GUIDE_TOPICS.PROJECTS,
    summary: 'Add a participant or change their project role.',
    scopeKind: 'division',
    before: ['The person must meet the eligibility rules for the selected project role.'],
    inputs: ['Project', 'Member', 'Project role'],
    success: 'The participant record and private channel access are reconciled.',
    activity: 'The participant and role change are posted in #bot-log.',
  }),
  entry({
    command: 'project-remove-member',
    title: 'Remove a project participant',
    topic: GUIDE_TOPICS.PROJECTS,
    summary: 'Remove a participant and their direct project-channel access.',
    scopeKind: 'division',
    before: ['The project must still be active or paused.'],
    inputs: ['Project', 'Member', 'Optional private reason'],
    success: 'The participant record and channel access are removed.',
    activity: 'The participant removal is posted in #bot-log without the private reason.',
  }),
  entry({
    command: 'project-update',
    title: 'Update a project',
    topic: GUIDE_TOPICS.PROJECTS,
    summary: 'Change a project name, expected end, status, or private notes.',
    scopeKind: 'division',
    before: ['The project must be active or paused.', 'The expected end cannot be before the start date.'],
    inputs: ['Project', 'Only the fields that should change'],
    success: 'Project data and the Discord channel are reconciled.',
    activity: 'Visible changes are posted in #bot-log. A notes-only update stays private.',
  }),
  entry({
    command: 'project-close',
    title: 'Close a project',
    topic: GUIDE_TOPICS.PROJECTS,
    summary: 'Complete a project, record its outcome, and move its channel to history.',
    scopeKind: 'division',
    before: ['The project must be active or paused.', 'Prepare an outcome and private final handover notes.'],
    inputs: ['Project', 'Outcome', 'Final notes'],
    success: 'The project is completed and its Discord channel is locked and moved to archive/history.',
    activity: 'The outcome and Discord state are posted in #bot-log; final notes are omitted.',
  }),
  entry({
    command: 'project-info',
    title: 'View project information',
    topic: GUIDE_TOPICS.LOOKUPS,
    summary: 'View a visible project, timeline, status, channel, and participants.',
    scopeKind: 'project',
    before: ['The project picker only returns projects you may view.'],
    inputs: ['Project'],
    success: 'The project information is shown only to you.',
    activity: 'Nothing is posted in #bot-log.',
  }),
]);

export const GUIDE_COMMAND_NAMES = Object.freeze(GUIDE_CATALOG.map((item) => item.command));

export function guideEntry(commandName) {
  return GUIDE_CATALOG.find((item) => item.command === commandName) ?? null;
}
